version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    # Add volumes if you need to persist data
    # volumes:
    #   - ./data:/app/data
